// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyCI3LZ0OKrx3D7a5wbWD3sXFmW4SEhGo-M',
    appId: '1:391084674285:web:28ff47e9c3a6b04e3ed0e4',
    messagingSenderId: '391084674285',
    projectId: 'hogar-3f60f',
    authDomain: 'hogar-3f60f.firebaseapp.com',
    storageBucket: 'hogar-3f60f.appspot.com',
    measurementId: 'G-GLSJP2JPJ5',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyD13w7pDxJJmbmqxmMZRAv1S1bnNMg2l6c',
    appId: '1:391084674285:android:65e323fc0c1a22a73ed0e4',
    messagingSenderId: '391084674285',
    projectId: 'hogar-3f60f',
    storageBucket: 'hogar-3f60f.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyCUOYQvFousbMWMu2nsOtYhQOU2cmUuwMY',
    appId: '1:391084674285:ios:219a8374ca6fc58a3ed0e4',
    messagingSenderId: '391084674285',
    projectId: 'hogar-3f60f',
    storageBucket: 'hogar-3f60f.appspot.com',
    iosClientId: '391084674285-it36l4qb2pskbah191mne3c5gsr27t4f.apps.googleusercontent.com',
    iosBundleId: 'com.tfg.appfirebase',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyCUOYQvFousbMWMu2nsOtYhQOU2cmUuwMY',
    appId: '1:391084674285:ios:219a8374ca6fc58a3ed0e4',
    messagingSenderId: '391084674285',
    projectId: 'hogar-3f60f',
    storageBucket: 'hogar-3f60f.appspot.com',
    iosClientId: '391084674285-it36l4qb2pskbah191mne3c5gsr27t4f.apps.googleusercontent.com',
    iosBundleId: 'com.tfg.appfirebase',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyCI3LZ0OKrx3D7a5wbWD3sXFmW4SEhGo-M',
    appId: '1:391084674285:web:e02ffaaef6948cbd3ed0e4',
    messagingSenderId: '391084674285',
    projectId: 'hogar-3f60f',
    authDomain: 'hogar-3f60f.firebaseapp.com',
    storageBucket: 'hogar-3f60f.appspot.com',
    measurementId: 'G-4GDER4SQ9Z',
  );
}
